### PR TITLE
Fix incorrect handling of env-var NEK_LOGFILE

### LINKED ISSUE #798: Correct boolean statement
I am getting a compiler warning about the following line in `core/chelpers.c`: 

```
  else if (envvar = getenv("NEK_LOGFILE")) {
    if (*sid >= 0) sprintf(logfile, "s%05d_", *sid);
    strcat(logfile + strlen(logfile), envvar);
    redirect = 1;
  }
```

That should be a `==` instead of a `=` inside the if statement. I don't think this is causing any bad behavior for my case, but wanted to note it because it's probably a mistake.

### PR DESCRIPTION
**Pull request by aprilnovak**
Closes #798

### CODE REVIEW

File: core/chelpers.c [hunk 1]
```diff
@@ -79,7 +79,7 @@ void set_stdout(char *f, int *sid, int flen)
   if (logfile[0] != '\0') {
     redirect = 1;
   } 
-  else if (envvar = getenv("NEK_LOGFILE")) {
+  else if (envvar == getenv("NEK_LOGFILE")) {
```
Comment (stgeke) [inline core/chelpers.c]: I think this block should read:
```
else if (getenv("NEK_LOGFILE")) {
    char *envvar = getenv("NEK_LOGFILE");
    if (*sid >= 0) sprintf(logfile, "s%05d_", *sid);
    strcat(logfile + strlen(logfile), envvar);
    redirect = 1;
}

```

**Review by stgeke — CHANGES_REQUESTED** [review]

File: core/chelpers.c (hunk 1 above)
Comment (aprilnovak) [reply core/chelpers.c]: You're probably right, I didn't look too closely at what this code does.
